#!/usr/bin/env bun
/**
 * Supabase Schema Verification Script
 *
 * Programmatically checks what tables exist in Supabase vs what the code expects.
 * Run this script to automatically update SCHEMA_STATUS.md with current state.
 *
 * Usage:
 *   bun run verify-schema.ts
 *
 * Requirements:
 *   - EXPO_PUBLIC_SUPABASE_URL in .env
 *   - SUPABASE_SERVICE_ROLE_KEY in .env (for admin access)
 */

// Workaround for TypeScript module resolution issue with @supabase/supabase-js
// @ts-ignore - Import works at runtime
import { createClient as supabaseCreateClient } from '@supabase/supabase-js';
import * as fs from 'fs';

// Load environment variables
const SUPABASE_URL = process.env.EXPO_PUBLIC_SUPABASE_URL;
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_URL || !SUPABASE_SERVICE_KEY) {
  console.error('❌ Missing environment variables:');
  console.error('   - EXPO_PUBLIC_SUPABASE_URL');
  console.error('   - SUPABASE_SERVICE_ROLE_KEY');
  process.exit(1);
}

// Create Supabase admin client
const supabase = supabaseCreateClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);

// Define expected tables by priority
const EXPECTED_TABLES = {
  critical: [
    'profiles',
    'food_entries',
    'fasting_sessions',
    'user_settings',
    'goals',
  ],
  mealPlanning: [
    'meal_plans',
    'meal_plan_entries',
    'recipes',
    'recipe_ingredients',
    'meal_templates',
  ],
  foodFeatures: [
    'favorite_foods',
  ],
  achievements: [
    'achievements',
    'achievement_types',
    'goal_milestones',
  ],
  coaching: [
    'coaches',
    'coach_purchases',
    'coach_reviews',
    'messages',
  ],
  subscription: [
    'subscriptions',
    'payment_methods',
    'invoices',
  ],
  analytics: [
    'step_tracking',
    'weight_logs',
  ],
};

interface TableStatus {
  name: string;
  exists: boolean;
  rowCount?: number;
  hasData: boolean;
  error?: string;
}

interface CategoryStatus {
  category: string;
  tables: TableStatus[];
  totalTables: number;
  existingTables: number;
  percentComplete: number;
}

/**
 * Check if a table exists in Supabase
 */
async function checkTableExists(tableName: string): Promise<TableStatus> {
  try {
    // Try to query the table
    const { error, count } = await supabase
      .from(tableName)
      .select('*', { count: 'exact', head: true })
      .limit(0);

    if (error) {
      // Table doesn't exist or no access
      return {
        name: tableName,
        exists: false,
        hasData: false,
        error: error.message,
      };
    }

    return {
      name: tableName,
      exists: true,
      hasData: (count ?? 0) > 0,
      rowCount: count ?? 0,
    };
  } catch (err) {
    return {
      name: tableName,
      exists: false,
      hasData: false,
      error: err instanceof Error ? err.message : 'Unknown error',
    };
  }
}

/**
 * Check all tables and categorize results
 */
async function verifyAllTables(): Promise<CategoryStatus[]> {
  const results: CategoryStatus[] = [];

  for (const [category, tables] of Object.entries(EXPECTED_TABLES)) {
    console.log(`\n🔍 Checking ${category} tables...`);

    const tableStatuses: TableStatus[] = [];

    for (const tableName of tables) {
      process.stdout.write(`   Checking ${tableName}...`);
      const status = await checkTableExists(tableName);

      if (status.exists) {
        console.log(` ✅`);
      } else {
        console.log(` ❌`);
      }

      tableStatuses.push(status);
    }

    const existingCount = tableStatuses.filter((t) => t.exists).length;
    const percentComplete = Math.round((existingCount / tables.length) * 100);

    results.push({
      category,
      tables: tableStatuses,
      totalTables: tables.length,
      existingTables: existingCount,
      percentComplete,
    });
  }

  return results;
}

/**
 * Generate markdown report
 */
function generateMarkdownReport(results: CategoryStatus[]): string {
  const timestamp = new Date().toISOString();

  let markdown = `# Supabase Schema Status

**Last Updated:** ${timestamp}
**Auto-generated by:** \`bun run verify-schema.ts\`

---

## 📊 Summary

`;

  // Overall summary
  const totalTables = results.reduce((sum, cat) => sum + cat.totalTables, 0);
  const existingTables = results.reduce((sum, cat) => sum + cat.existingTables, 0);
  const overallPercent = Math.round((existingTables / totalTables) * 100);

  markdown += `| Metric | Value |\n`;
  markdown += `|--------|-------|\n`;
  markdown += `| Total Expected Tables | ${totalTables} |\n`;
  markdown += `| Tables Found | ${existingTables} |\n`;
  markdown += `| Missing Tables | ${totalTables - existingTables} |\n`;
  markdown += `| Completion | ${overallPercent}% |\n`;

  markdown += `\n---\n\n`;

  // Category breakdown
  markdown += `## 📋 Category Breakdown\n\n`;

  for (const category of results) {
    const statusEmoji = category.percentComplete === 100 ? '✅' : category.percentComplete >= 50 ? '⚠️' : '❌';

    markdown += `### ${statusEmoji} ${category.category} (${category.percentComplete}% complete)\n\n`;
    markdown += `**Status:** ${category.existingTables}/${category.totalTables} tables exist\n\n`;

    markdown += `| Table | Status | Rows | Notes |\n`;
    markdown += `|-------|--------|------|-------|\n`;

    for (const table of category.tables) {
      const statusIcon = table.exists ? '✅' : '❌';
      const rowCount = table.exists ? (table.rowCount ?? 0) : '-';
      const notes = table.error ? `Error: ${table.error}` : table.hasData ? 'Has data' : 'Empty';

      markdown += `| \`${table.name}\` | ${statusIcon} | ${rowCount} | ${notes} |\n`;
    }

    markdown += `\n`;
  }

  // Missing tables section
  const missingTables = results.flatMap((cat) =>
    cat.tables.filter((t) => !t.exists).map((t) => ({ category: cat.category, table: t.name }))
  );

  if (missingTables.length > 0) {
    markdown += `---\n\n## ⚠️ Missing Tables (${missingTables.length})\n\n`;
    markdown += `These tables are expected by the code but don't exist in Supabase:\n\n`;

    for (const { category, table } of missingTables) {
      markdown += `- **${table}** (${category})\n`;
    }

    markdown += `\n### 🔧 How to Fix\n\n`;
    markdown += `1. Check migration files in \`/database/migrations/\`\n`;
    markdown += `2. Run migrations manually in Supabase SQL Editor\n`;
    markdown += `3. See SCHEMA_MIGRATION_CHECKLIST.md for details\n\n`;
  } else {
    markdown += `---\n\n## ✅ All Expected Tables Exist!\n\n`;
    markdown += `Your Supabase schema is fully up to date.\n\n`;
  }

  // Footer
  markdown += `---\n\n`;
  markdown += `## 📝 How to Update This Report\n\n`;
  markdown += `Run this command to regenerate:\n\n`;
  markdown += '```bash\n';
  markdown += `bun run verify-schema.ts\n`;
  markdown += '```\n\n';

  markdown += `**Generated:** ${new Date().toLocaleString()}\n`;

  return markdown;
}

/**
 * Main execution
 */
async function main() {
  console.log('🔍 Supabase Schema Verification\n');
  console.log('Connecting to:', SUPABASE_URL);
  console.log('');

  // Verify all tables
  const results = await verifyAllTables();

  // Generate markdown report
  const markdown = generateMarkdownReport(results);

  // Save to file using Node.js fs
  fs.writeFileSync('SCHEMA_STATUS.md', markdown, 'utf-8');

  console.log('\n✅ Report generated: SCHEMA_STATUS.md');

  // Print summary
  const totalTables = results.reduce((sum, cat) => sum + cat.totalTables, 0);
  const existingTables = results.reduce((sum, cat) => sum + cat.existingTables, 0);
  const missingTables = totalTables - existingTables;

  console.log('\n📊 Summary:');
  console.log(`   Total tables: ${totalTables}`);
  console.log(`   Existing: ${existingTables}`);
  console.log(`   Missing: ${missingTables}`);

  if (missingTables > 0) {
    console.log('\n⚠️  Some tables are missing. Check SCHEMA_STATUS.md for details.');
    process.exit(1);
  } else {
    console.log('\n✅ All expected tables exist!');
    process.exit(0);
  }
}

main().catch((error) => {
  console.error('❌ Error:', error);
  process.exit(1);
});
